### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by MatthewRuiz** [MatthewRuiz/Websites#2]
Things to do:
- [] Add consumables to chest.
- [] Multiple items if chest.
- [] Kill count.
- [] Time-based loot. As the game progresses, players are more likely to encounter better loot.
- [] Use consumables for health.
- [] Grant/lose health based off of random occurrences. i.e., +5 HP for apple, -30HP for fall damage, etc.
